[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26" # Solana version to use

[features]
seeds = true

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/merkle-distributor",
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.devnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.testnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.localnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[scripts]
test = "yarn mocha"
